### ISSUE TITLE
Issue-created docs folder

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#10]
Automated Review Comments
Issues in docs/Technical Requirementss.md:
  - (3, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')

**Comment by FAANG-star** [comment]
I got it.
