### ISSUE TITLE
Issue-deployed firebase-hosting and added new pages

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#18]
Automated Review Comments
Issues in .firebase/hosting.cHVibGlj.cache:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
Issues in .firebaserc:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in .github/workflows/firebase-hosting-pull-request.yml:
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in firebase.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in public/404.html:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
Issues in public/index.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in src/assets/LoginLogo.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
Issues in src/assets/adjustIcon.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/assets/dropDownArrow.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
Issues in src/components/CreateNewProgramFields/CreateNewProgramFields.jsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
Issues in src/components/HomeHeader/HomeHeader.jsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/components/InputFieldModule/InputFieldModule.jsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
Issues in src/components/LoginFields/LoginFields.jsx:
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in src/components/RegistrationFields/RegistrationFields.jsx:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
Issues in src/components/Tabbar/Tabbar.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
Issues in src/components/UserProgramCard/ExistingProgram.jsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
Issues in src/components/UserProgramCard/NoProgram.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/components/UserProgramCard/UserProgramCard.jsx:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
Issues in src/components/hooks/useFetchUserData.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserProgram.jsx:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
Issues in src/firebase/firebase.config.js:
  - (4, 'Hardcoded string found')
Issues in src/pages/CreateNewProgramPage.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
