### ISSUE TITLE
Issue-created protected routes and adjusted styles

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#23]
Automated Review Comments
Issues in src/components/Tabbar/Tabbar.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
Issues in src/pages/PagesRouter/ProtectedRoutes.jsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
