### ISSUE TITLE
Issue-home page header styles adjusting

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#27]
Automated Review Comments
Issues in src/components/HomeHeader/HomeHeader.jsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/pages/HomePage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')

**Comment by FAANG-star** [comment]
I got it.
