### ISSUE TITLE
Issue-carousel created, styled and added connection to DB

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#41]
Automated Review Comments
Issues in .firebase/hosting.YnVpbGQ.cache:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (192, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/components/Carousel/Carousel.jsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/components/Carousel/CarouselItem/CarouselItem.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in src/components/UserExercisesCard/UserExercisesCard.jsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in src/components/UserMealsCard/UserMealsCard.jsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMoveVideos.jsx:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by FAANG-star** [comment]
I got it.
