### ISSUE TITLE
Issue-carousel logic rewrited, admin page added

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#43]
Automated Review Comments
Issues in src/components/Carousel/Carousel.jsx:
  - (2, 'Hardcoded string found')
Issues in src/components/Carousel/CarouselItem/CarouselItem.jsx:
  - (5, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in src/components/UserExercisesCard/UserExercisesCard.jsx:
  - (2, 'Hardcoded string found')
Issues in src/components/UserMealsCard/UserMealsCard.jsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMealsData.jsx:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMoveVideos.jsx:
  - (1, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/pages/AdminPage.jsx:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
Issues in src/pages/PagesRouter/PagesRouter.jsx:
  - (1, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
