### ISSUE TITLE
Issue-Skeleton components | refactoring async code | refactoring cookies

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#50]
Automated Review Comments
Issues in .firebase/hosting.YnVpbGQ.cache:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
Issues in package-lock.json:
  - (4, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/components/HomeHeader/HomeHeader.jsx:
  - (2, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in src/components/HomeHeader/SkeletonHomeHeader.jsx:
  - (2, 'Hardcoded string found')
Issues in src/components/LoginFields/LoginFields.jsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in src/components/RegistrationFields/RegistrationFields.jsx:
  - (2, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/components/UserExercisesCard/SkeletonExerciseCard.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/UserExercisesCard/UserExercisesCard.jsx:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/components/UserMealsCard/UserMealsCard.jsx:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/components/UserProgramCard/SkeletonProgramCard.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/UserProgramCard/UserProgramCard.jsx:
  - (2, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
Issues in src/components/helpers/setAuthCookies.js:
  - (7, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMealsData.jsx:
  - (4, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMoveVideos.jsx:
  - (4, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserData.jsx:
  - (1, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserProgram.jsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
Issues in src/index.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/pages/HomePage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in src/pages/PagesRouter/NotAuthPages.jsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in src/pages/PagesRouter/ProtectedRoutes.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
