### ISSUE TITLE
Issue-added skeleton UI on profile avatar

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#57]
Automated Review Comments
Issues in package-lock.json:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (195, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (220, 'Line exceeds 80 characters')
  - (220, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Line exceeds 80 characters')
  - (224, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Line exceeds 80 characters')
  - (237, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (240, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Line exceeds 80 characters')
  - (250, 'Hardcoded string found')
  - (251, 'Line exceeds 80 characters')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (255, 'Line exceeds 80 characters')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (266, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (276, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Line exceeds 80 characters')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (285, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Line exceeds 80 characters')
  - (305, 'Hardcoded string found')
  - (306, 'Line exceeds 80 characters')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Line exceeds 80 characters')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Line exceeds 80 characters')
  - (322, 'Hardcoded string found')
  - (323, 'Line exceeds 80 characters')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Line exceeds 80 characters')
  - (335, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (336, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Line exceeds 80 characters')
  - (340, 'Hardcoded string found')
  - (341, 'Line exceeds 80 characters')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Line exceeds 80 characters')
  - (356, 'Hardcoded string found')
  - (357, 'Line exceeds 80 characters')
  - (357, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Line exceeds 80 characters')
  - (372, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Line exceeds 80 characters')
  - (383, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (384, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Line exceeds 80 characters')
  - (395, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (405, 'Line exceeds 80 characters')
  - (405, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Line exceeds 80 characters')
  - (413, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (418, 'Line exceeds 80 characters')
  - (418, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (423, 'Line exceeds 80 characters')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (426, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Line exceeds 80 characters')
  - (435, 'Hardcoded string found')
  - (436, 'Line exceeds 80 characters')
  - (436, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (438, 'Line exceeds 80 characters')
  - (438, 'Hardcoded string found')
  - (439, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Line exceeds 80 characters')
  - (448, 'Hardcoded string found')
  - (449, 'Line exceeds 80 characters')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (453, 'Line exceeds 80 characters')
  - (453, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
Issues in package.json:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/components/ProfileAvatar/ProfileAvatar.jsx:
  - (1, 'Hardcoded string found')
Issues in src/components/ProfileAvatar/SkeletonProfile.jsx:
  - (2, 'Hardcoded string found')
Issues in src/components/UserExercisesCard/SkeletonExerciseCard.jsx:
  - (3, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserProgram.jsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (53, 'Hardcoded string found')

**Comment by DamienDeLaCerda** [comment]
I got it.
