### ISSUE TITLE
Issue-refactoring to TypeScript

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#59]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/App.tsx:
  - (8, 'Hardcoded string found')
Issues in src/components/Carousel/Carousel.tsx:
  - (8, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in src/components/HomeHeader/HomeHeader.tsx:
  - (2, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/components/HomeHeader/SkeletonHomeHeader.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ProfileAvatar/ProfileAvatar.tsx:
  - (2, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in src/components/Tabbar/Tabbar.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/UserExercisesCard/SkeletonExerciseCard.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/UserExercisesCard/UserExercisesCard.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/components/UserMealsCard/UserMealsCard.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/components/UserProgramCard/ExistingProgram.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in src/components/UserProgramCard/NoProgram.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/components/UserProgramCard/SkeletonProgramCard.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/UserProgramCard/UserProgramCard.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMealsData.ts:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/hooks/useFetchMoveVideos.ts:
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserData.ts:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserProgram.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in src/index.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/types/types.ts:
  - (16, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')

**Comment by DamienDeLaCerda** [comment]
I got it.
