### ISSUE TITLE
Issue-create md file

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#6]
Automated Review Comments
Issues in Technical Requirementss.md:
  - (7, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')

**Comment by DamienDeLaCerda** [comment]
I got it.
