### ISSUE TITLE
Issue-Refactored to TypeScript

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#61]
Automated Review Comments
Issues in .firebase/hosting.YnVpbGQ.cache:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
Issues in src/components/ActiveNotificationModal/ActiveNotificationModal.tsx:
  - (2, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/components/AdjustProgramFields/AdjustProgramFields.tsx:
  - (3, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
Issues in src/components/Carousel/CarouselItem/CarouselItem.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/HomeHeader/HomeHeader.tsx:
  - (30, 'Hardcoded string found')
Issues in src/components/LoginFields/LoginFields.tsx:
  - (3, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in src/components/NotificationListItem/NotificationListItem.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
Issues in src/components/NotificationNewsList/NotificationNewsList.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
Issues in src/components/NotificationNewsList/SkeletonNotification.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ProfileAvatar/ProfileAvatar.tsx:
  - (28, 'Hardcoded string found')
Issues in src/components/ProfileAvatar/SkeletonProfile.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/RegistrationFields/RegistrationFields.tsx:
  - (7, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
Issues in src/components/helpers/setAuthCookies.ts:
  - (11, 'Hardcoded string found')
Issues in src/components/hooks/useFetchUserNotifications.ts:
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/pages/PagesRouter/NotAuthPages.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/pages/PagesRouter/ProtectedRoutes.tsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by FAANG-star** [comment]
I got it.
