### ISSUE TITLE
Issue-Update README.md

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#70]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')

**Comment by FAANG-star** [comment]
I got it.
