### ISSUE TITLE
Issue-Update Technical Requirementss.md

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/victu-frontend#8]
Automated Review Comments
Issues in Technical Requirementss.md:
  - (5, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
